security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        account_user_provider:
            id: App\Security\AccountUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|build)/
            security: false
        main:
            pattern: ^/
            security: true
            lazy: true
            provider: account_user_provider
            entry_point: App\Security\AccountEntryPoint

    access_control:
        - { path: ^/, roles: ROLE_LIVROR_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
