twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes: ['theme/form.html.twig']
    globals: 
        env:
            app:
                name: '%app.name%'
                env: '%app.env%'
                currency: '%app.currency%'
                locale: '%app.locale%'
                max_results: '%app.max_results%'
            versioning:
                version: '%versioning.version%'
                version_hash: '%versioning.version_hash%'
                release_date: '%versioning.release_date%'
        HubUrlGenerator: "@App\\Service\\HubUrlGenerator"

when@test:
    twig:
        strict_variables: true
