twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes: ['theme/form.html.twig']
    globals: 
        env:
            app:
                name: '%app.name%'
                env: '%app.env%'
                currency: '%app.currency%'
                locale: '%app.locale%'
                default_limit: '%app.default_limit%'
                max_limit: '%app.max_limit%'
                enable_prefetch: '%app.enable_prefetch%'
                index_autoload: '%app.index_autoload%'
            versioning:
                version: '%versioning.version%'
                version_hash: '%versioning.version_hash%'
                release_date: '%versioning.release_date%'

when@test:
    twig:
        strict_variables: true
