twig:
    file_name_pattern: '*.twig'
    form_themes: ['theme/form.html.twig']
    globals: 
        app:
            version: '%livror.version%'
            release_date: '%livror.release_date%'

when@test:
    twig:
        strict_variables: true
