twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals: 
        app:
            version: '%livror.version%'

when@test:
    twig:
        strict_variables: true
