twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes: ['theme/form.html.twig']
    globals: 
        versioning:
            version: '%versioning.version%'
            release_date: '%versioning.release_date%'

when@test:
    twig:
        strict_variables: true
