when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        faker:
            locale: fr_FR
        persistence:
            flush_once: true
        make_factory:
            add_hints: false
            default_namespace: 'App\Fixtures\Factory'
        make_story:
            default_namespace: 'App\Fixtures\Story'

    # If you use the `make:factory --test` command, you may need to uncomment the following.
    # See https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#generate
    #services:
    #    App\Tests\Factory\:
    #        resource: '%kernel.project_dir%/tests/Factory/'
    #        autowire: true
    #        autoconfigure: true

when@test: *dev
