# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.name: '%env(string:APP_NAME)%'
    app.env: '%env(string:APP_ENV)%'
    app.currency: '%env(string:APP_CURRENCY)%'
    app.locale: '%env(string:APP_LOCALE)%'
    app.request_timeout: '%env(int:APP_REQUEST_TIMEOUT)%'
    app.max_results: '%env(int:APP_MAX_RESULTS)%'
    app.html_validation: '%env(bool:APP_HTML_VALIDATION)%'
    hub.base_url: '%env(string:HUB_BASE_URL)%'
    hub.account_route: '%env(string:HUB_ACCOUNT_ROUTE)%'

imports:
    - { resource: 'version.yaml' }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            
    App\Form\:
        resource: '../src/Form'
        tags: ['form.type']
        arguments:
            $htmlValidation: '%app.html_validation%'

    App\Form\GameType:
        arguments:
            $htmlValidation: '%app.html_validation%'
            $currency: '%app.currency%'

    App\Service\SteamSearchManager:
        arguments:
            $timeout: '%app.request_timeout%'
            $locale: '%app.locale%'
            $currency: '%app.currency%'

    App\Service\HubUrlGenerator:
        arguments:
            $hubBaseUrl: '%hub.base_url%'
            $hubAccountRoute: '%hub.account_route%'

when@test: &test
    services:
        App\Tests\Mock\ApiMock:
            decorates: 'http_client'
            arguments: ['@App\Tests\Mock\ApiMock.inner']

when@dev: *test
